apiVersion: bmc.tinkerbell.org/v1alpha1
kind: Job
metadata:
  name: {{ .JobName }}
  namespace: {{ .Namespace }}
spec:
  machineRef:
    name: {{ .ServerName }}
    namespace: {{ .Namespace }}
  tasks:
    - powerAction: "on"
