// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOwners = `-- name: CountActiveOwners :one
select count(*)
from organization_memberships m
join roles r on r.id = m.role_id
where m.organization_id = $1 and m.status = 'active' and r.name = 'Owner'
`

func (q *Queries) CountActiveOwners(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOwners, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasOrganizationPermission = `-- name: HasOrganizationPermission :one
select exists (
	select 1
	from organization_memberships m
	join role_permissions rp on rp.role_id = m.role_id
	where m.organization_id = $1
		and m.user_id = $2
		and m.status = 'active'
		and rp.permission = $3
) as has_permission
`

type HasOrganizationPermissionParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Permission     string      `json:"permission"`
}

func (q *Queries) HasOrganizationPermission(ctx context.Context, arg HasOrganizationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrganizationPermission, arg.OrganizationID, arg.UserID, arg.Permission)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
