// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBillingProfile = `-- name: GetBillingProfile :one
select id, organization_id, stripe_customer_id, billing_email, company_name, tax_id, line1, line2, city, state, postal_code, country, created_at, updated_at
from billing_profiles
where organization_id = $1
`

func (q *Queries) GetBillingProfile(ctx context.Context, organizationID pgtype.UUID) (BillingProfile, error) {
	row := q.db.QueryRow(ctx, getBillingProfile, organizationID)
	var i BillingProfile
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StripeCustomerID,
		&i.BillingEmail,
		&i.CompanyName,
		&i.TaxID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
select id, organization_id, stripe_invoice_id, status, amount_due, amount_paid, period_start, period_end, created_at, updated_at
from invoices
where organization_id = $1
order by period_start desc
`

func (q *Queries) ListInvoices(ctx context.Context, organizationID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StripeInvoiceID,
			&i.Status,
			&i.AmountDue,
			&i.AmountPaid,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
