// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type BillableService struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	OrderID            pgtype.UUID        `json:"order_id"`
	ServiceType        string             `json:"service_type"`
	ServiceID          pgtype.UUID        `json:"service_id"`
	BillingMode        string             `json:"billing_mode"`
	Status             string             `json:"status"`
	BillingStartedAt   pgtype.Timestamptz `json:"billing_started_at"`
	BillingEndedAt     pgtype.Timestamptz `json:"billing_ended_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextInvoiceAt      pgtype.Timestamptz `json:"next_invoice_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type BillableServicePrice struct {
	ID                pgtype.UUID        `json:"id"`
	BillableServiceID pgtype.UUID        `json:"billable_service_id"`
	PriceType         string             `json:"price_type"`
	Description       string             `json:"description"`
	Unit              string             `json:"unit"`
	UnitPriceCents    int64              `json:"unit_price_cents"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	Currency          string             `json:"currency"`
	EffectiveFrom     pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo       pgtype.Timestamptz `json:"effective_to"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type BillingAccount struct {
	ID                         pgtype.UUID        `json:"id"`
	OrganizationID             pgtype.UUID        `json:"organization_id"`
	StripeCustomerID           pgtype.Text        `json:"stripe_customer_id"`
	BillingEmail               string             `json:"billing_email"`
	Currency                   string             `json:"currency"`
	Status                     string             `json:"status"`
	PaymentTerms               string             `json:"payment_terms"`
	CreditBalanceCents         int64              `json:"credit_balance_cents"`
	AutoRechargeEnabled        bool               `json:"auto_recharge_enabled"`
	AutoRechargeThresholdCents pgtype.Int8        `json:"auto_recharge_threshold_cents"`
	AutoRechargeAmountCents    pgtype.Int8        `json:"auto_recharge_amount_cents"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type BillingPeriod struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	BillableServiceID pgtype.UUID        `json:"billable_service_id"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	Status            string             `json:"status"`
	InvoiceRecordID   pgtype.UUID        `json:"invoice_record_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type BillingProfile struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	BillingEmail     string             `json:"billing_email"`
	CompanyName      string             `json:"company_name"`
	TaxID            pgtype.Text        `json:"tax_id"`
	Line1            pgtype.Text        `json:"line1"`
	Line2            pgtype.Text        `json:"line2"`
	City             pgtype.Text        `json:"city"`
	State            pgtype.Text        `json:"state"`
	PostalCode       pgtype.Text        `json:"postal_code"`
	Country          pgtype.Text        `json:"country"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CreditLedger struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	BillingAccountID  pgtype.UUID        `json:"billing_account_id"`
	Type              string             `json:"type"`
	AmountCents       int64              `json:"amount_cents"`
	BalanceAfterCents int64              `json:"balance_after_cents"`
	SourceType        pgtype.Text        `json:"source_type"`
	SourceID          pgtype.UUID        `json:"source_id"`
	Description       string             `json:"description"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	Email           string             `json:"email"`
	RoleID          pgtype.UUID        `json:"role_id"`
	InvitedByUserID pgtype.UUID        `json:"invited_by_user_id"`
	Token           string             `json:"token"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	StripeInvoiceID string             `json:"stripe_invoice_id"`
	Status          string             `json:"status"`
	AmountDue       int64              `json:"amount_due"`
	AmountPaid      int64              `json:"amount_paid"`
	PeriodStart     pgtype.Timestamptz `json:"period_start"`
	PeriodEnd       pgtype.Timestamptz `json:"period_end"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceLineItem struct {
	ID                pgtype.UUID        `json:"id"`
	InvoiceRecordID   pgtype.UUID        `json:"invoice_record_id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	BillableServiceID pgtype.UUID        `json:"billable_service_id"`
	Description       string             `json:"description"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	Unit              string             `json:"unit"`
	UnitPriceCents    int64              `json:"unit_price_cents"`
	AmountCents       int64              `json:"amount_cents"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type InvoiceRecord struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	StripeInvoiceID pgtype.Text        `json:"stripe_invoice_id"`
	InvoiceNumber   pgtype.Text        `json:"invoice_number"`
	Status          string             `json:"status"`
	SubtotalCents   int64              `json:"subtotal_cents"`
	TaxCents        int64              `json:"tax_cents"`
	TotalCents      int64              `json:"total_cents"`
	AmountPaidCents int64              `json:"amount_paid_cents"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	FinalizedAt     pgtype.Timestamptz `json:"finalized_at"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                      pgtype.UUID        `json:"id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	Status                  string             `json:"status"`
	OrderType               string             `json:"order_type"`
	SubtotalCents           int64              `json:"subtotal_cents"`
	TaxCents                int64              `json:"tax_cents"`
	TotalCents              int64              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	Metadata                []byte             `json:"metadata"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	RoleID         pgtype.UUID        `json:"role_id"`
	Status         string             `json:"status"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PaymentMethod struct {
	ID                    pgtype.UUID        `json:"id"`
	OrganizationID        pgtype.UUID        `json:"organization_id"`
	StripePaymentMethodID string             `json:"stripe_payment_method_id"`
	Brand                 string             `json:"brand"`
	Last4                 string             `json:"last4"`
	ExpMonth              int32              `json:"exp_month"`
	ExpYear               int32              `json:"exp_year"`
	IsDefault             bool               `json:"is_default"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProvisioningJob struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	ServerID          pgtype.UUID        `json:"server_id"`
	RackID            string             `json:"rack_id"`
	RequestedByUserID pgtype.UUID        `json:"requested_by_user_id"`
	ImageID           string             `json:"image_id"`
	Hostname          string             `json:"hostname"`
	Status            string             `json:"status"`
	FailureReason     pgtype.Text        `json:"failure_reason"`
	CorrelationID     string             `json:"correlation_id"`
	CommandMessageID  pgtype.Text        `json:"command_message_id"`
	RequestedAt       pgtype.Timestamptz `json:"requested_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProvisioningJobEvent struct {
	ID                pgtype.UUID        `json:"id"`
	ProvisioningJobID pgtype.UUID        `json:"provisioning_job_id"`
	EventType         string             `json:"event_type"`
	Message           string             `json:"message"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Rack struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Location        string             `json:"location"`
	Status          string             `json:"status"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RackAgent struct {
	ID              pgtype.UUID        `json:"id"`
	RackID          string             `json:"rack_id"`
	AgentID         string             `json:"agent_id"`
	Version         string             `json:"version"`
	Status          string             `json:"status"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RackMessage struct {
	ID          pgtype.UUID        `json:"id"`
	MessageID   string             `json:"message_id"`
	Direction   string             `json:"direction"`
	RackID      string             `json:"rack_id"`
	ServerID    pgtype.UUID        `json:"server_id"`
	JobID       pgtype.UUID        `json:"job_id"`
	MessageType string             `json:"message_type"`
	Status      string             `json:"status"`
	Payload     []byte             `json:"payload"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	IsSystemRole   bool               `json:"is_system_role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID         pgtype.UUID        `json:"id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	Permission string             `json:"permission"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Server struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	RackID         string             `json:"rack_id"`
	Status         string             `json:"status"`
	BmcAddress     string             `json:"bmc_address"`
	MacAddress     string             `json:"mac_address"`
	Provisionable  bool               `json:"provisionable"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StripeEvent struct {
	ID            pgtype.UUID        `json:"id"`
	StripeEventID string             `json:"stripe_event_id"`
	EventType     string             `json:"event_type"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UsageLedger struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	BillableServiceID pgtype.UUID        `json:"billable_service_id"`
	UsageType         string             `json:"usage_type"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	Unit              string             `json:"unit"`
	UnitPriceCents    int64              `json:"unit_price_cents"`
	AmountCents       int64              `json:"amount_cents"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Auth0Sub  string             `json:"auth0_sub"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
