// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
insert into organizations (name, slug, created_by_user_id)
values ($1, $2, $3)
returning id, name, slug, created_by_user_id, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.CreatedByUserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationForUser = `-- name: GetOrganizationForUser :one
select o.id, o.name, o.slug, o.created_by_user_id, o.created_at, o.updated_at
from organizations o
join organization_memberships m on m.organization_id = o.id
where o.id = $1 and m.user_id = $2 and m.status = 'active'
`

type GetOrganizationForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationForUser(ctx context.Context, arg GetOrganizationForUserParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationForUser, arg.ID, arg.UserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
select o.id, o.name, o.slug, o.created_by_user_id, o.created_at, o.updated_at
from organizations o
join organization_memberships m on m.organization_id = o.id
where m.user_id = $1 and m.status = 'active'
order by o.created_at desc
`

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
update organizations
set name = $2, slug = $3, updated_at = now()
where id = $1
returning id, name, slug, created_by_user_id, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
