// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
insert into projects (organization_id, name, slug)
values ($1, $2, $3)
returning id, organization_id, name, slug, created_at, updated_at
`

type CreateProjectParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Slug           string      `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
select id, organization_id, name, slug, created_at, updated_at
from projects
where organization_id = $1 and id = $2
`

type GetProjectParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrganizationID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
select id, organization_id, name, slug, created_at, updated_at
from projects
where organization_id = $1
order by name
`

func (q *Queries) ListProjects(ctx context.Context, organizationID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
