// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveOwners(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	GetBillingProfile(ctx context.Context, organizationID pgtype.UUID) (BillingProfile, error)
	GetOrganizationForUser(ctx context.Context, arg GetOrganizationForUserParams) (Organization, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error)
	HasOrganizationPermission(ctx context.Context, arg HasOrganizationPermissionParams) (bool, error)
	ListInvoices(ctx context.Context, organizationID pgtype.UUID) ([]Invoice, error)
	ListOrganizationsForUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error)
	ListProjects(ctx context.Context, organizationID pgtype.UUID) ([]Project, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
