// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const getUserByAuth0Sub = `-- name: GetUserByAuth0Sub :one
select id, auth0_sub, email, name, created_at, updated_at
from users
where auth0_sub = $1
`

func (q *Queries) GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0Sub, auth0Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
insert into users (auth0_sub, email, name)
values ($1, $2, $3)
on conflict (auth0_sub) do update
set email = excluded.email,
	name = excluded.name,
	updated_at = now()
returning id, auth0_sub, email, name, created_at, updated_at
`

type UpsertUserParams struct {
	Auth0Sub string `json:"auth0_sub"`
	Email    string `json:"email"`
	Name     string `json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Auth0Sub, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
